architecture: glow

learning_rate: 0.000025
optimizer: adam
weight_decay: 0.00005
n_epochs: 1000
batch_size: 64

inherit_p: false

loss:
  nll:
    weight: 1.0
  kd:
    name: mse
    weight: 0
  perceptual:
    name: l1
    checkpoint: /home/vdklyukin/nf_distillation/data/weights/vgg16-397923af.pth
    weight: 0

seed: 42

gpus: 1
num_workers: 10

fid_samples: 2048
inception_checkpoint: /home/vdklyukin/nf_distillation/data/weights/inception_v3.pth

to_test: false
track_grad_norm: false
roc_auc: false

neptune:
  project_name: vklyukin/norm-flows
  experiment_name: distillation
  tags:
    - celeba
    - student
    - uptrain
    - NF-368
