architecture: glow

learning_rate: 0.0001
optimizer: adamax
weight_decay: 0.
n_epochs: 30
batch_size: 64

inherit_p: false

loss:
  nll:
    weight: 1.
  kd:
    name: mse
    weight: 0.
  perceptual:
    name: l1
    checkpoint: ./data/weights/vgg16-397923af.pth
    weight: 0.

seed: 42

gpus: 1
num_workers: 16

fid_samples: 2048
inception_checkpoint: ./data/weights/inception_v3.pth

to_test: false
track_grad_norm: false
roc_auc: false

neptune:
  project_name: mrartemev.me/norm-flows
  experiment_name: distillation
  api_key: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIzN2Y0YjdlNS00MDkyLTRjZDYtOTM5Yi1kMDJkYTk5YzExY2QifQ==
  tags:
    - celeba
    - teacher
    - 8_bits
    - kd