architecture: glow

learning_rate: 0.0005
optimizer: adam
n_epochs: 1000
batch_size: 128

inherit_p: false

loss:
  nll:
    weight: 0.8
  kd:
    name: mse
    weight: 0.1
  perceptual:
    name: vgg
    checkpoint: ./data/weights/vgg16-397923af.pth
    weight: 0.1

seed: 42

gpus: 1
num_workers: 10

fid_samples: 2048
inception_checkpoint: ./data/weights/inception_v3.pth

to_test: false
track_grad_norm: false

neptune:
  project_name: vklyukin/norm-flows
  experiment_name: distillation
  tags:
    - cifar10
    - perceptual
    - mse
