architecture: glow

learning_rate: 0.0000
optimizer: adam
n_epochs: 1
batch_size: 128

inherit_p: false

loss:
  nll:
    weight: 1
  kd:
    name: mse
    weight: 0

seed: 42

gpus: 1
num_workers: 10
fid_samples: 2048

to_test: false
track_grad_norm: false

neptune:
  project_name: vklyukin/norm-flows
  experiment_name: distillation
  tags:
    - mse
    - cifar10
