architecture: glow

learning_rate: 0.0005
weight_decay: 0.
optimizer: adam
n_epochs: 1000
batch_size: 16384

inherit_p: false

loss:
  nll:
    weight: 0.85
  kd:
    name: mse
    weight: 0.075
  perceptual:
    name: l1
    weight: 0.075

metric:
  ks:
    bins: 20
  efficiency:
    make_ratio: True
    bins: 10
    thresholds: [0.05,0.10,0.25,0.50,0.75,0.90,0.95]

seed: 42

gpus: 1
num_workers: 10
fid_samples: -1

to_test: false
track_grad_norm: false
roc_auc: true

neptune:
  project_name: mrartemev.me/norm-flows
  experiment_name: tabular
  tags:
    - rich
    - small
    - student
    - distillation
    - perceptual
