architecture: maf

learning_rate: 0.0005
optimizer: adam
weight_decay: 0.
n_epochs: 10000
batch_size: 65536

inherit_p: false

loss:
  nll:
    weight: 0.9
  kd:
    name: mse
    weight: 0.1
  perceptual:
    name: l1
    weight: 0.

seed: 42

gpus: 1
num_workers: 2

fid_samples: -1
roc_auc: false

to_test: false
track_grad_norm: false

neptune:
  project_name: vklyukin/norm-flows
  experiment_name: tabular
  tags:
    - bsds300
    - student
    - kd
    - made
