architecture: glow

learning_rate: 0.0005
optimizer: adam
weight_decay: 0.
n_epochs: 400000
batch_size: 512

inherit_p: false

loss:
  nll:
    weight: 1.
  kd:
    name: mse
    weight: 0.
  perceptual:
    name: l1
    weight: 0.

seed: 42

gpus: 1
num_workers: 4

fid_samples: -1
roc_auc: false

to_test: false
track_grad_norm: false

neptune:
  project_name: mrartemev.me/norm-flows
  experiment_name: tabular
  api_key: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIzN2Y0YjdlNS00MDkyLTRjZDYtOTM5Yi1kMDJkYTk5YzExY2QifQ==
  tags:
    - tabular
    - teacher
    - power
    - kd
    - perceptual
